### ISSUE TITLE
A few UX issues

### ISSUE THREAD

**Issue by innocenzi** [Sammyjo20/saloon-docs#33]
Hey there, when setting up Saloon and following the docs, I noticed that the code selection wasn't working well at all:

https://user-images.githubusercontent.com/16060559/228839427-3966507b-e61a-40b1-a901-f63642f7cef7.mp4

This is the case in both Chrome and Firefox.

On Firefox, there's an additional issue: the selection doesn't get copied. Sometimes it just copies part of it:

https://user-images.githubusercontent.com/16060559/228840052-002ad792-1244-4ea1-ba1a-c269436ee98d.mp4

Another thing, the aside at the right of the page are `div`s, not `a`s. So they don't behave as links, eg. I can't middle-click to open in a new tab.

**Comment by Sammyjo20** [comment]
Hey @innocenzi many thanks for reporting this.

Unfortunately, I don't have the control to be able to fix an issue like this as Saloon's documentation is hosted with Gitbook. I will however report this issue with Gitbook directly and ask if they could take a look.

Many thanks!

**Comment by innocenzi** [comment]
I didn't realize this was using Gitbook, my bad!

I recommend VitePress if you're ever looking for another docs setup 👍🏻
