### ISSUE TITLE
Package exceptions

### ISSUE THREAD

**Issue by asamofal** [Sammyjo20/saloon-docs#56]
Hi! Could you clarify something for me, please. Why `send` method of the Connector class throw some low-level PHP exceptions, I expected to have something from the [Saloon exceptions](https://docs.saloon.dev/the-basics/handling-failures#response-exceptions) there.

My code looks something like this:
![image](https://github.com/Sammyjo20/saloon-docs/assets/2729547/0767e9f1-17e3-43c2-a6f6-74cd82a725c9)

But the PhpDoc of `send` method says:
<img width="524" alt="image" src="https://github.com/Sammyjo20/saloon-docs/assets/2729547/6f51a75c-a93c-4311-a1d0-a9ff212b6180">

Maybe the scope of exceptions that the package can throw can be limited to `SaloonException` (as the lowest one in the package hierarchy)?

**Comment by Sammyjo20** [comment]
Hey @asamofal - this is a very good point! I believe these lower-level PHP exceptions have been created as a result of me generating the PHP DocBlocks in my IDE. It's seen some of the code I've written with ReflectionClass, and maybe other places where `Throwable` is type-hinted and specified that it could get thrown.

I usually just ignore these exceptions as they shouldn't affect your code. Should I remove them from the Saloon codebase? I've not considered an issue like this before but it would make sense to remove them if they're not related to Saloon, right?

**Comment by asamofal** [comment]
@Sammyjo20 Well, in my opinion, yes. You've already listed the exceptions that clients should be concerned about (pretty good hierarchy, btw). Let's follow the documentation declarations in the code :) 

An IDE is our friend, and it's a good idea to pay attention to its advice. Therefore, the package's `@throws` must accurately reflect the truth. 
Using custom exceptions is preferable, as it makes handling them in the client code easier, without crossing into native PHP exceptions. As in my example above, I want to be able to catch just any of `SaloonExeception`.

**Comment by Sammyjo20** [comment]
Hey @asamofal I've gone through some of the codebase and removed some of the unnecessary exceptions that were listed in the docblocks - this should tidy things up for you and your try-catch blocks should look a lot nicer.

**Comment by asamofal** [comment]
@Sammyjo20 Thank you so much for your work! I'm so grateful for all the effort you've put in.

p.s. I apologize for creating the issue in the wrong repository, I noticed it too late
